# Generated by Django 5.1.1 on 2024-09-25 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produits', models.CharField(max_length=100)),
                ('nom_destinataire', models.CharField(max_length=100)),
                ('adr_destinataire', models.CharField(max_length=100)),
                ('num_destinataire', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('en cours', 'En cours'), ('livré', 'Livré'), ('annulé', 'Annulé')], default='en cours', max_length=20)),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
