# Generated by Django 5.1.1 on 2024-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
         migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, blank=True, null=True),
        ),
    ]
