# Generated by Django 5.1.1 on 2024-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0005_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
          migrations.RemoveField(
            model_name='profile',
            name='phone_number',
            
        ),
    ]
