# Generated by Django 5.1.1 on 2024-09-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0006_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colis',
            name='status',
            field=models.CharField(choices=[('en cours', 'Pending'), ('livré', 'Accpted'), ('annulé', 'Refused')], default='en cours', max_length=20),
        ),
    ]
