# Generated by Django 5.1.1 on 2024-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0007_colis_date_envoi_alter_colis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
