# Generated by Django 5.1.1 on 2024-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0010_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='date_distribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
    ]
